apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: lab3app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kaitokissurlips/frontend-image:v1
        ports:
        - containerPort: 5000
