apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lab3app
spec:
  type: LoadBalancer
  ports:
  - port: 80 # External port exposed by the LoadBalancer
    targetPort: 5000 # Port on the pods
  selector:
    app: backend
